# Generated by Django 3.2.7 on 2021-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='atleta',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='atletaf',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='frecord',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='record',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
