# Generated by Django 3.2.7 on 2021-11-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0003_auto_20211111_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
    ]
