# Generated by Django 3.2.7 on 2021-11-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0004_remove_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('image_cover', models.ImageField(upload_to='')),
                ('cada', models.CharField(blank=True, max_length=100)),
                ('ama', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FotoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=300)),
                ('torneo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncuyo.torneo')),
            ],
        ),
    ]
