# Generated by Django 3.2.7 on 2021-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0005_fotourl_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fecha',
            field=models.DateField(default=None),
        ),
    ]
