# Generated by Django 3.2.7 on 2021-11-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0006_torneo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='ama',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='cada',
        ),
    ]
