# Generated by Django 3.2.7 on 2021-11-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uncuyo', '0007_auto_20211114_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['-fecha']},
        ),
    ]
